{% set name = "openscienceplot_matplotlib" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 13fa19478f37175540940adf22ec143f89b58ba58f6f78508939c914c7d012c3

build:
  number: 1
  noarch: python
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - h5py

test:
  imports:
    - openscienceplot_matplotlib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tdegeus/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Iterative ensemble averages
  description: Iterative ensemble averages
  doc_url: https://github.com/tdegeus/{{ name }}
  dev_url: https://github.com/tdegeus/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
